### PR TITLE
Upgrade Opencast PHP Library to 1.8.0 + Api Version setting (OC 16 Support) + Moodle 4.4 Required Changes

### LINKED ISSUE #62: Opencast PHP Library Upgrade (v.1.8.0)
This is a release announcement:
https://github.com/elan-ev/opencast-php-library/releases/tag/1.7.0
https://github.com/elan-ev/opencast-php-library/releases/tag/1.8.0

List of changes:
https://github.com/elan-ev/opencast-php-library/milestone/5?closed=1

### Important to know
- Support for Opencast 16
- Playlist endpoint
- Ingest accepts workflow config params

### Code Enhancements Suggestions:
As for Moodle Plugin, there is no specific Opencast API Version checker offered in the settings. This can lead to a burden on the Opencast-PHP-Library to check that version every time an instance is created. The API version is important to be checked by the library in order to offer some or part of the api features introduced in each version.
Therefore, I suggest and will provide this extra setting to the settings of `tool_opencast` plugin, which improves the performance by almost 10%!

### PR DESCRIPTION
**Pull request by ferishili**
This PR fixes #62.

It consists of two part:
- The upgrade of the Opencast PHP Library to 1.8.0 which is important to use the plugin for Opencast 16
- A new setting is instroduced: "Opencast API Version", which helps improve the performance when configured correctly!

### New settings:
**UPDATE**: The api version setting has been removed, in favor of hard-coding the api version (if any) as it is a developer matter, not an admin to take care of!
<del>Admins are now able to add the api version for each instance:</del>
- <del>configuring it improves performance by eliminating an automated step by which the api version is extracted.</del>
- <del>If not sure how to find it just use this link format to get is: [your opencast address]/docs.html?path=/api#getversiondefault-8</del>

- <del>By leaving it empty, it does what it did like before!</del>

Please note:
This PR also contains the required changes to Moodle 4.4, otherwise the Actions "CI"s won't work

### CODE REVIEW

**Comment by ferishili** [comment]
Because this PR is being use in some new changes in block_opencast plugin, specifically for the sake of passing workflow configurations into the ingest api, therefore a new branch has been created: https://github.com/Opencast-Moodle/moodle-tool_opencast/tree/oc-16-support

**Comment by geichelberger** [comment]
I think we should hardcode the minimum required API version, as it should be a developer thing to decide which API version is needed if we want to support different feature sets based on a configuration to support several Opencast Versions; it should be a curated version List, maybe with just the Opencast Version as the API version only changes with major releases.

**Comment by ferishili** [comment]
> it should be a curated version List, maybe with just the Opencast Version as the API version only changes with major releases.

Hi @geichelberger,
if I understood your suggestion correctly, at the end of the day (and for the sake of backward compatibility of OC versions) we need to get the **Opencast Version** either automatically (it is done via **sysinfo** endpoint - which is not under api) or by user (admin) **input** through **settings**.
I am correct? What is your opinion?

**Comment by ferishili** [comment]
The api version setting has been reverted and it went back to the normal automatic way like before for now, until we decide if it is necessary to add hard-coded api versions!

**Pull request merged**
